### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by grimnight** [xyproto/in#3]
The program doesn't seem to be working for me.

```shell
~/Dev/GHQ/github.com/xyproto/in main
❯ in build touch test
2023/08/15 00:14:13 chdir /home/grimnight/Dev/GHQ/github.com/xyproto/in/build/build: no such file or directory
```

**Comment by xyproto** [comment]
Thanks for reporting! I'll reproduce and fix the issue.

**Comment by xyproto** [comment]
I switched from Go to Rust and I think this issue is fixed now as well.

Please re-open this issue if there should be further issues with this.
